#This is a script to run the MESA models through Malik GWAS Summary #Statistics
#!/bin/bash
cd /home/egeoffroy/MetaXcan/software/

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Cardioembolic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005842/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/ALL_Cardioembolic_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Cardioembolic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005842/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFA_Cardioembolic_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Cardioembolic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005842/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFHI_Cardioembolic_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/CAU_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/CAU_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Cardioembolic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005842/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/CAU_Cardioembolic_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Cardioembolic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005842/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/HIS_Cardioembolic_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Ischemic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005843/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/ALL_Ischemic_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Ischemic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005843/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFA_Ischemic_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Ischemic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005843/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFHI_Ischemic_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/CAU_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/CAU_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Ischemic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005843/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/CAU_Ischemic_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Ischemic_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005843/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/HIS_Ischemic_stroke.csv





/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Large_artery_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005840/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/ALL_Large_artery_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Large_artery_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005840/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFA_Large_artery_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Large_artery_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005840/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFHI_Large_artery_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/CAU_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/CAU_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Large_artery_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005840/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/CAU_Large_artery_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Large_artery_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005840/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/HIS_Large_artery_stroke.csv




/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Small_Vessel_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005841/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/ALL_Small_vessel_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Small_Vessel_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005841/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFA_Small_vessel_stroke.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Small_Vessel_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005841/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFHI_Small_vessel_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/CAU_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/CAU_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Small_Vessel_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005841/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/CAU_Small_vessel_stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Small_Vessel_stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005841/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/HIS_Small_vessel_stroke.csv


/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005838/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/ALL_Stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005838/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFA_Stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005838/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/AFHI_Stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/CAU_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/CAU_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005838/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/CAU_Stroke.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/Stroke/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/MalikR_29531354_GCST005838/harmonised/ --gwas_file_pattern ".*tsv.gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Malik/MESA/HIS_Stroke.csv
