
#For Glomerular filtration rate in non-Europeans
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/MESA_ALL.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/MESA_AFA.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/MESA_AFHI.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz  --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/MESA_HIS.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/CAU_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/CAU_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008058/MESA_CAU.csv

#For Glomerular filtration rate in Europeans
#For Glomerular filtration rate
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/MESA_ALL.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/MESA_AFA.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/MESA_AFHI.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz  --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/MESA_HIS.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/CAU_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/CAU_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/ --gwas_file_pattern ".*gz"  --snp_column RSID --effect_allele_column Allele1 --non_effect_allele_column Allele2  --beta_column Effect --pvalue_column P-value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Wuttke/GCST008059/MESA_CAU.csv
