#This is a script to run the MESA models through Horikoshi GWAS Summary Statistics
#!/bin/bash
cd /home/egeoffroy/MetaXcan/software/

python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/HorikoshiM_27680694_GCST005146/BW3_Transethnic_summary_stats.txt.gz --snp_column rsid --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/MESA/ALL.csv
python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/HorikoshiM_27680694_GCST005146/BW3_Transethnic_summary_stats.txt.gz --snp_column rsid --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/MESA/AFA.csv
python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/HorikoshiM_27680694_GCST005146/BW3_Transethnic_summary_stats.txt.gz --snp_column rsid --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/MESA/AFHI.csv
python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/HorikoshiM_27680694_GCST005146/BW3_Transethnic_summary_stats.txt.gz --snp_column rsid --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/MESA/HIS.csv
python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/CAU_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/CAU_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/HorikoshiM_27680694_GCST005146/BW3_Transethnic_summary_stats.txt.gz --snp_column rsid --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Horikoshi/MESA/CAU.csv


