#!/bin/bash

nohup python3 finemap.py --fastenloc --pop ALL --LD /home/wheelerlab3/db2fastenloc/ldetect-data/AFR_fourier_ls-all.bed --pheno_id White_blood --gwas_SS /home/elyse/Wojcik_build37/31217584-GCST008039-EFO_0004309-build37.f.tsv.gz --meqtl /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/meqtl_sorted_ALL_Epi_GEX_data_sidno_Nk-20.txt --genemap /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/gencode.v18.annotation.parsed.txt --geno /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/genotypes/ &  

nohup python3 finemap.py --fastenloc --pop AFA --LD /home/wheelerlab3/db2fastenloc/ldetect-data/AFR_fourier_ls-all.bed --pheno_id White_blood --gwas_SS /home/elyse/Wojcik_build37/31217584-GCST008039-EFO_0004309-build37.f.tsv.gz --meqtl /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/meqtl_sorted_AFA_Epi_GEX_data_sidno_Nk-20.txt --genemap /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/gencode.v18.annotation.parsed.txt --geno /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/genotypes/ &

nohup python3 finemap.py --fastenloc --pop AFHI --LD /home/wheelerlab3/db2fastenloc/ldetect-data/AFR_fourier_ls-all.bed --pheno_id White_blood --gwas_SS /home/elyse/Wojcik_build37/31217584-GCST008039-EFO_0004309-build37.f.tsv.gz --meqtl /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/meqtl_sorted_AFHI_Epi_GEX_data_sidno_Nk-20.txt --genemap /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/gencode.v18.annotation.parsed.txt --geno /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/genotypes/ &  
nohup python3 finemap.py --fastenloc --pop HIS --LD /home/wheelerlab3/db2fastenloc/ldetect-data/AFR_fourier_ls-all.bed --pheno_id White_blood --gwas_SS /home/elyse/Wojcik_build37/31217584-GCST008039-EFO_0004309-build37.f.tsv.gz --meqtl /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/meqtl_sorted_HIS_Epi_GEX_data_sidno_Nk-20.txt --genemap /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/gencode.v18.annotation.parsed.txt --geno /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/genotypes/ &  
nohup python3 finemap.py --fastenloc --pop CAU --LD /home/wheelerlab3/db2fastenloc/ldetect-data/AFR_fourier_ls-all.bed --pheno_id White_blood --gwas_SS /home/elyse/Wojcik_build37/31217584-GCST008039-EFO_0004309-build37.f.tsv.gz --meqtl /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/meqtl_sorted_CAU_Epi_GEX_data_sidno_Nk-20.txt --genemap /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/expression/gencode.v18.annotation.parsed.txt --geno /home/wheelerlab3/files_for_revisions_plosgen/en_v7/prepare_data/genotypes/ &  
