#!/bin/bash
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Body_mass_index/WojcikGL_31217584_GCST008025/SumStats/WojcikG_PMID_invn_rbmi_alls.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Body_mass_index/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Chronic_kidney/WojcikGL_31217584_GCST008026/SumStats/WojcikG_PMID_ckd_analysis.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Chronic_kidney/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Coffee/WojcikGL_31217584_GCST008028/SumStats/WojcikG_PMID_lncoffee.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Coffee/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/C-reactive/WojcikGL_31217584_GCST008055/SumStats/WojcikG_PMID_lncrp.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/C-reactive/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Diabetes/WojcikGL_31217584_GCST008048/SumStats/WojcikG_PMID_T2D_bmi.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Diabetes/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Diastolic_blood/WojcikGL_31217584_GCST008029/SumStats/WojcikG_PMID_dbp_adjmeds_win.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Diastolic_blood/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/End_renal/WojcikGL_31217584_GCST008031/SumStats/WojcikG_PMID_esrd_analysis.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/End_renal/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Fasting_glucose/WojcikGL_31217584_GCST008033/WojcikG_PMID_lnFI.adjBMI.invn.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Fasting_glucose/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Fasting_insulin/WojcikGL_31217584_GCST008033/SumStats/WojcikG_PMID_lnFI.adjBMI.invn.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Fasting_insulin/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Glomerular/WojcikGL_31217584_GCST008030/SumStats/WojcikG_PMID_egfrckdepi.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Glomerular/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/HDL_cholesterol/WojcikGL_31217584_GCST008035/SumStats/WojcikG_PMID_hdl_adjmeds.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/HDL_cholesterol/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Height53/WojcikGL_31217584_GCST008053/SumStats/WojcikG_PMID_invn_rheight_alls.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Height53/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Hemoglobin/WojcikGL_31217584_GCST008034/SumStats/WojcikG_PMID_HbA1c.adjBMI.invn.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Hemoglobin/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Hypertension/WojcikGL_31217584_GCST008036/SumStats/WojcikG_PMID_htn.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Hypertension/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/LDL_cholesterol/WojcikGL_31217584_GCST008037/SumStats/WojcikG_PMID_ldl_adjmeds.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/LDL_cholesterol/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Mean_corpuscular_hemoglobin/WojcikGL_31217584_GCST008038/SumStats/WojcikG_PMID_mchc.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Mean_corpuscular_hemoglobin/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Platelet/WojcikGL_31217584_GCST008039/SumStats/WojcikG_PMID_platelets.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Platelet/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/PR/WojcikGL_31217584_GCST008042/SumStats/WojcikG_PMID_pr_interval.gz   -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/PR/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/QRS_duration/WojcikGL_31217584_GCST008054/SumStats/WojcikG_PMID_qrs_interval.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/QRS_duration/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/QT_interval/WojcikG_PMID_qt_interval.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/QT_interval/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Smoking/WojcikGL_31217584_GCST008027/SumStats/WojcikG_PMID_lncigs_per_day_excl_nonsmk.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Smoking/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Systolic_blood/WojcikGL_31217584_GCST008044/SumStats/WojcikG_PMID_sbp_adjmeds_win.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Systolic_blood/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Total_cholesterol/WojcikGL_31217584_GCST008045/SumStats/WojcikG_PMID_tc_adjmeds.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Total_cholesterol/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Triglyceride/WojcikGL_31217584_GCST008046/SumStats/WojcikG_PMID_lntriglycerides_adjmeds.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Triglyceride/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip50/WojcikGL_31217584_GCST008050/SumStats/WojcikG_PMID_invn_rwhrbmi_fs.out.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip50/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip51/WojcikGL_31217584_GCST008051/SumStats/WojcikG_PMID_invn_rwhrbmi_ms.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip51/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip52/WojcikG_PMID_invn_rwhrbmi_alls.gz  -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip52/WojcikG_hg38.out
Rscript Summary_Statistics/scripts/lifover_WojcikG.R --gwas /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/White_blood/WojcikGL_31217584_GCST008049/SumStats/WojcikG_PMID_lnwbc.out.gz -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/White_blood/WojcikG_hg38.out

Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Body_mass_index/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Body_mass_index/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Chronic_kidney/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Chronic_kidney/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Coffee/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Coffee/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/C-reactive/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/C-reactive/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Diabetes/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Diabetes/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Diastolic_blood/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Diastolic_blood/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/End_renal/WojcikG_hg38.out  --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/End_renal/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Fasting_glucose/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Fasting_glucose/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Fasting_insulin/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Fasting_insulin/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Glomerular/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Glomerular/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/HDL_cholesterol/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/HDL_cholesterol/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Height53/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Height53/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Hemoglobin/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Hemoglobin/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Hypertension/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Hypertension/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/LDL_cholesterol/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/LDL_cholesterol/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Mean_corpuscular_hemoglobin/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Mean_corpuscular_hemoglobin/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Platelet/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Platelet/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/PR/WojcikG_hg38.out  --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/PR/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/QRS_duration/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/QRS_duration/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/QT_interval/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/QT_interval/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Smoking/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Smoking/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Systolic_blood/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Systolic_blood/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Total_cholesterol/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Total_cholesterol/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Triglyceride/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Triglyceride/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip50/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip50/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip51/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip51/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip52/WojcikG_hg38.out --LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/Waist-hip52/LD_assigned.txt.gz
Rscript Summary_Statistics/scripts/test_binning_assign.R --assoc /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/White_blood/WojcikG_hg38.out--LD /home/egeoffroy/fourier_ls-all.bed -o /home/egeoffroy/Summary_Statistics/Summary_Stats/Wojcik/White_blood/LD_assigned.txt.gz
