#!/bin/bash
cd MetaXcan/software
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/DemenaisF_29273806_GCST005212/harmonised/ --gwas_file_pattern ".*gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/MESA/ALL.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/DemenaisF_29273806_GCST005212/harmonised/ --gwas_file_pattern ".*gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/MESA/AFA.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/DemenaisF_29273806_GCST005212/harmonised/ --gwas_file_pattern ".*gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/MESA/AFHI.csv
#/home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/DemenaisF_29273806_GCST005212/harmonised/ --gwas_file_pattern ".*gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/MESA/AFHI.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/CAU_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/CAU_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/DemenaisF_29273806_GCST005212/harmonised/ --gwas_file_pattern ".*gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/MESA/CAU.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/DemenaisF_29273806_GCST005212/harmonised/ --gwas_file_pattern ".*gz" --snp_column variant_id --effect_allele_column effect_allele --non_effect_allele_column other_allele --beta_column beta --pvalue_column p_value --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Demenais/MESA/HIS.csv
