library(data.table)
library(dplyr)
library(ggplot2)

pcs <- read.table("/home/elyse/HapMap_models/plink_files/HapMap_PC_autosome.eigenvec", header =F, stringsAsFactors = F)
print(nrow(pcs))
pcdf <- data.frame(pcs) %>% rename(FID=V1, IID=V2, PC1=V3,PC2=V4,PC3=V5,PC4=V6,PC5=V7,PC6=V8,PC7=V9,PC8=V10,PC9=V11,PC10=V12)
write.table(pcdf, "/home/elyse/HapMap_models/HapMap_autosome_PC.txt", quote = F, row.names=F)
#print(pcdf)
hapmap_pop <- read.table("/home/elyse/HapMap3-genotypes/relationships_w_pops_121708.txt", header = T, stringsAsFactors=F) %>% select(IID, population)
hapmap <- c("CHB", 'MKK', 'YRI', 'LWK', 'MEX', 'JPT', 'GIH')
hapmap_pop <- subset(hapmap_pop, population %in% hapmap)
print(hapmap_pop)
#hapmap_pop <- filter(hapmap_pop, population == hapmap)
#hapmap_pop <- na.omit(hapmap_pop)
#popinfo <- mutate(popinfo, pop=ifelse(is.na(pop),'GWAS', as.character(pop)))
#table(popinfo$pop)
#print(hapmap_pop)

popinfo <- merge(hapmap_pop,pcdf,by="IID")
#print(unique(popinfo$population))
#popinfo <- mutate(popinfo, population=ifelse(is.na(population),'GWAS', as.character(population)))
#table(popinfo$population) #popinfo <- na.omit(popinfo)
#print(popinfo)
#hapmap <- c("CHB", "MKK", "JPT", "GIH", "LWK", "YRI", "MEX")
#popinfo <- filter(popinfo,population==hapmap)
popinfo <- na.omit(popinfo)
print(popinfo)
write.table(popinfo, "/home/elyse/HapMap_models/ALL_PCs.txt", quote=F, row.names=F)
#hm3 <- filter(popinfo, grepl('NA',IID))
#print(gwas)
#print(hm3)
###PCA Plot 1 (PC1 vs PC2)
cbp1 <- c("#999999", "#E69F00", "#56B4E9", "#F8766D",
          "#F0E442", "#00BA38", "#619CFF")
p <- ggplot() +geom_point(data=popinfo,aes(x=PC2,y=PC3,col=population))+ theme_bw() + scale_colour_manual(values=cbp1) #+ scale_colour_brewer(palette="Set1")
#ggsave("PCA_HapMap_autosome/HapMap_PCA_2_3.png", p)


p2 <- ggplot() +geom_point(data=popinfo,aes(x=PC1,y=PC3,col=population))+ theme_bw() + scale_colour_manual(values=cbp1) #+ scale_colour_brewer(palette="Set1")
ggsave("PCA_HapMap_autosome/HapMap_PCA_1_3.png", p2)

p3 <- ggplot() +geom_point(data=popinfo,aes(x=PC1,y=PC2,col=population))+ theme_bw() + scale_colour_manual(values=cbp1) #+ scale_colour_brewer(palette="Set1")
#ggsave("PCA_HapMap_autosome/HapMap_PCA_1_2.png", p3)

eval <- c(127.178, 50.2452, 8.81423, 6.59185, 5.96545, 2.87583, 2.73768, 2.67613, 2.64198, 2.61955)
#Calcuate proportion variance explained by each PC:
eval<-round(eval/sum(eval),3)
eval<-cbind.data.frame(eval,c(1,2,3,4,5,6,7,8,9,10))
colnames(eval)<-c("percent_var", "PC")
p1 <- ggplot(data=eval, aes(x=PC, y=percent_var)) + geom_point() + geom_line() + scale_x_continuous(breaks = 1:10) + ggtitle("Proportion of variance explained")
#ggsave("PCA_HapMap_autosome/scree_plot.png", p1)
