#!/bin/bash
cd /home/egeoffroy/MetaXcan/software/

#For 007483_additive_all/
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007483_additive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007483_additive_all/MESA_ALL.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007483_additive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007483_additive_all/MESA_AFA.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007483_additive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007483_additive_all/MESA_AFHI.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007483_additive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007483_additive_all/MESA_HIS.csv

#For 007493_recessive_all
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007493_recessive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007493_recessive_all/MESA_ALL.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007493_recessive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007493_recessive_all/MESA_AFA.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007493_recessive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007493_recessive_all/MESA_AFHI.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007493_recessive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007493_recessive_all/MESA_HIS.csv

#For 007500_additive_all
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007500_additive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007500_additive_all/MESA_ALL.csv
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007500_additive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007500_additive_all/MESA_AFA.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007500_additive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007500_additive_all/MESA_AFHI.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007500_additive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007500_additive_all/MESA_HIS.csv

#For 007501_recessive_all
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007501_recessive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007501_recessive_all/MESA_ALL.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007501_recessive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007501_recessive_all/MESA_AFA.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007501_recessive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007501_recessive_all/MESA_AFHI.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007501_recessive_all/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/007501_recessive_all/MESA_HIS.csv

#For Recessive_All_Five_Populations
/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/ALL_imputed_10_peer_3_pcs__v2.db --covariance /home/egeoffroy/MESA/ALL_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/Recessive_All_Five_Populations/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/Recessive_All_Five_Populations/MESA_ALL.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFA_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFA_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/Recessive_All_Five_Populations/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/Recessive_All_Five_Populations/MESA_AFA.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/AFHI_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/AFHI_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/Recessive_All_Five_Populations/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/Recessive_All_Five_Populations/MESA_AFHI.csv

/home/egeoffroy/anaconda2/bin/python ./MetaXcan.py --model_db_path /home/egeoffroy/MESA/HIS_imputed_10_peer_3_pcs_v2.db --covariance /home/egeoffroy/MESA/HIS_nested_cv_all_covariances_10_peer_3pcs.txt.gz --gwas_folder /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/Recessive_All_Five_Populations/ --gwas_file_pattern ".*gz"  --snp_column snpname --effect_allele_column ref --non_effect_allele_column alt --beta_column beta --pvalue_column pvalue --output_file /home/egeoffroy/Summary_Statistics/Summary_Stats/Justice/Recessive_All_Five_Populations/MESA_HIS.csv
