library(dplyr)
library(ggplot2)
CHB_expression <- read.table("/home/elyse/hapmap_expression_ensid/CHB_expression_ens.txt", header=T)
JPT_expression <- read.table("/home/elyse/hapmap_expression_ensid/JPT_expression_ens.txt", header =T)
YRI_expression <- read.table("/home/elyse/hapmap_expression_ensid/YRI_expression_ens.txt", header =T)
MKK_expression <- read.table("/home/elyse/hapmap_expression_ensid/MKK_expression_ens.txt", header =T)
LWK_expression <- read.table("/home/elyse/hapmap_expression_ensid/LWK_expression_ens.txt", header =T)
GIH_expression <- read.table("/home/elyse/hapmap_expression_ensid/GIH_expression_ens.txt", header =T)
MEX_expression <- read.table("/home/elyse/hapmap_expression_ensid/MEX_expression_ens.txt", header =T)
Combined_expression <- merge(JPT_expression,CHB_expression,by="PROBE_ID")
Combined_expression <- merge(Combined_expression,YRI_expression,by="PROBE_ID")
Combined_expression <- merge(Combined_expression,MKK_expression,by="PROBE_ID")
Combined_expression <- merge(Combined_expression,LWK_expression,by="PROBE_ID")
Combined_expression <- merge(Combined_expression,GIH_expression,by="PROBE_ID")
Combined_expression <- merge(Combined_expression,MEX_expression,by="PROBE_ID")
write.table(Combined_expression, file="/home/elyse/HapMap_models/combined_expression.txt", quote=F,row.names=F)
